namespace Ecommere.Payment.Infrastructure
{
    public static class PaymentDbInitializer
    {
        public static async Task InitializeAsync(PaymentDbContext db)
        {
            await db.Database.EnsureCreatedAsync();
            // No seed needed – payments are generated by saga.
        }
    }
}
